name: package
run-name: packaging plugin
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          mkdir -p plugin/site-packages
          Copy-Item -Path ${{ env.pythonLocation }}/lib/tkinter -Destination plugin/site-packages -Recurse
          Copy-Item -Path ${{ env.pythonLocation }}/tcl -Destination plugin/site-packages -Recurse
          pip install -r requirements.txt --target plugin/site-packages
          curl -LO https://www.python.org/ftp/python/3.9.13/python-3.9.13-embed-amd64.zip
          7z x python-3.9.13-embed-amd64.zip -o* -y
          Move-Item -Path python-3.9.13-embed-amd64/python.exe -Destination plugin/
          Move-Item -Path python-3.9.13-embed-amd64/python39.zip -Destination plugin/
          Move-Item -Path src/* -Destination plugin/
          Remove-Item plugin/site-packages/bin/*
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: plugin-windows
      #     path: plugin
      - name: Zip
        run: |
          zip -r plugin plugin/
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./plugin.zip
          asset_name: plugin_win_amd64.zip
          asset_content_type: application/zip
